export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
export const START = 'START';
export const HANDLE_SEARCH_TERM = 'HANDLE_SEARCH_TERM';
export const HANDLE_KEY_UP = 'HANDLE_KEY_UP';